/geometrySetup/selectDetector MicroDiamond

/geometrySetup/enableWaterPhantom true

# detector dimensions (or DE stage of the Telescope)
/geometrySetup/detectorDimension/setWidth 100 um
/geometrySetup/detectorDimension/setThickness 8 um

# the following only affect the Telescope detector
#/geometrySetup/detectorDimension/secondStage/setWidth 500 um
#/geometrySetup/detectorDimension/secondStage/setThickness 500 um

# the following only affect the WaterPixel detector
#/geometrySetup/setupWaterPixel/selectKinScoring 0

/geometrySetup/useMultipleSV true
/geometrySetup/multipleSVsetup/setSpacing 50 um
/geometrySetup/multipleSVsetup/setBreadth 50000 um

/geometrySetup/detectorPosition/setDepth 10 mm

/geometrySetup/detectorPosition/setMicroDiamondAngle 0 deg
