/geometrySetup/selectDetector MicroDiamond

/geometrySetup/enableWaterPhantom true

# detector dimensions (or DE stage of the Telescope)
/geometrySetup/detectorDimension/setWidth 100 um
/geometrySetup/detectorDimension/setThickness 8 um

# the following only affect the Telescope detector
#/geometrySetup/detectorDimension/secondStage/setWidth 500 um
#/geometrySetup/detectorDimension/secondStage/setThickness 500 um

/geometrySetup/useMultipleSV true
/geometrySetup/multipleSVsetup/setBreadth 5000 um

/geometrySetup/detectorPosition/setDepth 10 mm

/geometrySetup/applyChanges

